version: '2.4'
services:
  dev:
    build:
      context: ../
      target: dev
    working_dir: /home/node/app
    command: /bin/sh -c "while sleep 1; do :; done"
    environment:
      HISTFILE: '/root/.bashhistory/.bash_history'
      DEV_ENV: container
    ports:
      - 24538:24538
    volumes:
      - ../:/home/node/app
      - bash-history:/root/.bashhistory
      - $HOME/.ssh:/root/.ssh

volumes:
  bash-history:
