name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:18.16.0-bullseye
    env:
      DEV_ENV: container
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            node-modules-${{ hashFiles('yarn.lock') }}
            node-modules-

      - name: Install Node packages
        run: |
          yarn install --frozen-lockfile

      - name: Run linter
        run: yarn lint .
      - name: Run prettier
        run: yarn prettier

      - name: Build
        run: yarn build

      - name: Run tests
        run: yarn test:all
